# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shovon Datta Rony
title: Junior System Engineer
email: ronydatta@protonmail.com
website: ronydatta.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ronydatta
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: shovondattarony
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://ronydatta.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shovon Datta Rony and I'm a system engineer. Iam a hardworking and ambitious individual with a great passion for the cybersecurity and cloud industry I have excellent communication skills, enabling me to effectively communicate with a wide range of people that also enables me highly capable of team leading Proficient in a range of modern tools and technologies including intrusion detection/prevention system, machine learning, python php I would definitely mention that I am someone who can easily adapt to different environments and learn quickly

  

content:
  - title: Research Interest # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Mainly Interested in   
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            url: #github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This one of the ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          <mark>Network security</mark> <mark>Network traffic analysis</mark> <mark>Malware analysis & attribution</mark> <mark>IoT malware detection</mark> <mark>Security and privacy</mark> <mark>Machine learning</mark> <mark>Imbalanced classification</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sita New Multimedia Sdn. Bhd.
        link: www.sita.com.my
        # link_text: boringcompany.com
        sub_title: Junior System Engineer
        caption: January 2017 - Present
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Installing, maintaining, and troubleshooting of Linux server, deploying application such as CRM, ERP, HRMS, POS, IP‑PBX etc.
            - Server virtualization using open source tools such as Proxmox.
            - Identifying requirements to define, plan, and implement solutions for clients.
            - Developing and maintaining programs and scripts aiding the operation and automation of administrative tasks using scripting languages (bashand Python).
            - Installing and maintaining server based security systems.
            - Monitoring security incidents with extended detection response (XDR) using Wazuh.
            - Web Administration (CPanel, Wordpress, OpenCart)
            - Implemented several API microservices in Node.js Koa and in the serverless AWS Lambda functions.
            - Built an enterprise monitoring system (EMS) using Icinga which monitors network and system services such as ping, dhcp, http, ssl, snmp, ftp, apache, databases, ssh, etc.
            - Deployed a centralized dashboard and monitoring environment (ELK stack, Grafana, InfluxDB) which gather system metrics as well as application data from database.
            - Coordinate with vendors to resolve hardware and 3rd party software problems.
            - Backup/restore virtual machines and server configuration.
            - Maintain source code and create documentation using Gitlab.
            - Provide training to intern.



      - layout: left
        title: Sita New Multimedia Sdn. Bhd.
        link: www.sita.com.my
        # link_text: boringcompany.com
        sub_title: Intern
        caption: October 2016 - December 2016
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Learning about all the network equipment and their monitoring tools.
            - Creating VPN clients for remote users.
            - Commissioning decommissioning on‑premise Linux servers.
            - Learn about and contribute to the development of products (ERP, CRM, HRMS, Call‑center)
            - Present accomplishments and internship take‑aways.

      - layout: left
        title: MyCom Technology (ASUS authorised service partner)
        link: https://mycom.com.my/
        # link_text: boringcompany.com
        sub_title: Computer Technician
        caption: January 2016 - Present
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Set up hardware, install and configure software and drivers.
            - Maintain and repair hardware equipment (e.g. display, wan card, thermal, speaker, keyboard, touch‑pad).
            - Spare parts distribution.
            - Perform unit and system testing.
            - Manage system security options such as firewall and antivirus in computers to maintain privacy and protection from attacks.
            - Provide technical support and issue resolution to users via multiple remote assistance platforms.
            - Troubleshoot system failures or bugs and provide solutions to restore functionality.
            - Keep records of repairs and fixes for future reference.
            - Offer timely technical support and teach users how to utilize computers correctly.
            - Prepare weekly and monthly report for management.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Malaya
        caption: 2022
        sub_title: Master of Computer Science (Applied Computing)
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Thesis Title: A Comparative Analysis On Class Imbalance In Network Traffic Classification
          - Supervisor: Associate Prof. TS. Dr. Nor Badrul Anuar Bin Juma’at
          - Co‑supervisor: Prof. Ts. Dr. Miss Laiha Binti Mat Kiah
          - CGPA: 3.75/4.00


      - layout: left
        title: Lincoln University College
        caption: 2017
        sub_title: Bachelor of Computer Science (Hons.)
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Major: Network Technology and Cybersecurity
          - Supervisor: Dr. Divya Midhun Chakkaravarthy
          - CGPA: 3.81/4.00
          
          
  - title: Extracurricular Activity # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LUC (Lincoln University College) Linux Club
        caption: Aug. 2016 ‑ Sep. 2016
        sub_title: Trainer
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Provided hands‑on Linux (desktop + server) training in a dedicated Linux laboratory.
          - Explained filesystem and basic network configuration.
          - Taught how to install LAMP (Linux, Apache, MySQL & PHP) stack on Ubuntu server
          - Introduced Github and technical forum (Stack Overflow).    
          
      - layout: left
        title: LITS (Lincoln IT Society)
        caption: Sep. 2014 ‑ Jun. 2016
        sub_title: MEMBER & CO‑LEADER AT 2016
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Organised seminars, workshops and meetings for skill developments.
          - Provided ICT services to other departments.
          - Designed banners and brochures to raise awareness.
          - Designed certificates for participant. 
          - Conducted survey of learning management systems’ user experience.
          - Introduced open source operating system and PC software in different colleges. 
          
          
      - layout: left
        title: Bangladesh Red Crescent Society (BDRCS) 
        caption: Mar. 2010 ‑ Dec. 2012
        sub_title: VOLUNTEER STAFF
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Planned and organised blood donation camp in different places.
          - Created awareness about blood donation and its importance.
          - Encouraged people to donate blood.
          - Attended first aid training.           
                 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my above mentioned interests, some of my other interests and hobbies are:
      - Reading novels
      - Debating
      - Gaming
      - Exploring and testing new technology & gadgets
      - Playing football & cricket
      - Hanging out  with friends

      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
